EVAL_SET_BASE = './datasets/feret-meb-vars/fb'
TRAIN_SET_BASE = './datasets/feret-meb-vars/fa'
PATH_STOM = './datasplits/subjtomeb_colorferet.json'
PATH_FTOS =  './datasplits/fa_filepath_to_subject_colorferet.json'
VGG_WEIGHTS_PATH = './vggface/weights/plain-vgg-trained.ckpt'
SAVE_FOLDER = './output/euclidean_32_subjects'
EVAL_SAMPLE_SIZE = 196 # number of images per subject used to evaluate the network 
EPOCHS = 5
BATCH_SIZE = 49
LEARNING_RATE = 0.001
CHECKPOINT = 8
SUBJ_FOR_TRAINING = sorted(os.listdir(TRAIN_SET_BASE))[:32]
